### ISSUE TITLE
Doesn't show list of beacons

### ISSUE THREAD

**Issue by monksinha** [Beaconstac/EddystoneScanner-iOS-SDK#5]
I wrote a simple code, without the tableView and it outputs nothing, can you please look into it and see if its an issue? Peace!
//
//  ViewController.swift
//  ES3
//
//  Created by Utkarsh Sinha on 27/2/19.
//  Copyright © 2019 ORTech. All rights reserved.
//

    
import UIKit
import EddystoneScanner
import UserNotifications

class ViewController: UIViewController {
    
   let scanner = EddystoneScanner.Scanner()
   var timer : Timer?
    
    var beaconList = [Beacon]()
    
    var state = 1 //monitor Slider switch's value
    
    
    @IBOutlet weak var Switch: UISwitch!
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        
        
        // Do any additional setup after loading the view, typically from a nib.
        
        scanner.startScanning()
        scanner.delegate = self as? ScannerDelegate
        
    }
    
    
    
    func didUpdateScannerState(scanner: EddystoneScanner.Scanner, state: State)
    {
        print(state)
    }
    
    
    func didFindBeacon(scanner: EddystoneScanner.Scanner, beacon: Beacon)
    {
        beaconList.append(beacon)
      
    }
    
    
    func didLoseBeacon(scanner: EddystoneScanner.Scanner, beacon: Beacon)
    {
        guard let index = beaconList.index(of: beacon)
            else
        {
            return
        }
        beaconList.remove(at: index)
    }
    
    
    
    func didUpdateBeacon(scanner: EddystoneScanner.Scanner, beacon: Beacon)
    {
        guard let index = beaconList.index(of: beacon)
            else {
                  beaconList.append(beacon)
                  return
                }
        beaconList[index] = beacon
    }
    
    
    
    @IBAction func Switch(_ sender: UISwitch)
    {
       state+=1
        if state%2==0
        {
            startScanning()
        }
        else
        {
          stopScanning()
        }
    }
    
    
    
    func startScanning()
    {
       
     print(scanner.nearbyBeacons)
    print(beaconList)
        print(beaconList.count)
    }
    
    
    func stopScanning()
    {
        
    }
    
    override func didReceiveMemoryWarning()
    {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    
    
    
    
    
}

**Comment by sachinmobstac** [comment]
@monksinha, Which beacons are you using to test? Can you check if your Bluetooth is on?

**Comment by sachinmobstac** [comment]
Closing this since no word from @monksinha.
